# Generated by Django 6.0.1 on 2026-01-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=30, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_iva', models.DecimalField(decimal_places=2, default=0.21, max_digits=4)),
            ],
        ),
    ]
